version: '3'
services:
  art-backend:
    build: ./Dockerfile-backend
    command: npm start
    volumes:
      - ./backend:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:9850"
  art-frontend:
    build: ./Dockerfile-fronend
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "8001:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
